### PR TITLE
Update MainActivity.java

### PR DESCRIPTION
**Pull request by rshrc**
Messaging Functionalities Added

### CODE REVIEW

**Review by yashovardhan99 — APPROVED** [review]
Accepted your change. Thanks!

**Comment by yashovardhan99** [comment]
@Rishi110 Next time please use more meaningful commit messages such as "Added media capabilities" instead of just "Update MainActivity.java"

**Comment by rshrc** [comment]
bitcoin_image
bitcoin_image2
bitcoin_image3
ethereum_image
ethereum_image1
ripple

Here you go, the resource files

**Comment by yashovardhan99** [comment]
@Rishi110 I think you put this in the wrong repo...
Anyway, thanks

**Comment by rshrc** [comment]
i uploaded it in my repo also, please have a look. Thanks!

**Comment by yashovardhan99** [comment]
@Rishi110 checked it! Thanks!
Expect me to get working on it from tomorrow or Saturday.

**Pull request merged**
